defaults:
  - override /trainer_cfg@_global_: base_sft
  - override /model_cfg@_global_: qwen14b
  - override /data_cfg@_global_: teacher_bespoke_stratos
  - _self_

bf16: true
tf32: false
num_train_epochs: 3

save_strategy: epoch
save_steps: 1
do_eval: false

eval_strategy: steps
eval_steps: 20

per_device_train_batch_size: 1
gradient_accumulation_steps: 16

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

learning_rate: 2.0e-04
weight_decay: 1e-4
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1e-8
max_grad_norm: 1.0

lr_scheduler_type: cosine
warmup_ratio: 0.05

logging_steps: 1
logging_strategy: steps
packing: true
max_seq_length: 4096
per_device_eval_batch_size: 2

wandb_project: RLT_96GB_SFT
wandb_group_name: teacher_sft
wandb_run_name: teacher_${trainer_log_name}_${max_seq_length}ctx
output_dir: results/step-1_SFT_${exp_name}
