defaults:
  - override /model_cfg@_global_: qwen7bi
  - override /data_cfg@_global_: teacher_bespoke_stratos
  - override /trainer_cfg@_global_: grpo_mono_96gb  # Use 96GB trainer
  - _self_

# Can use larger models with 96GB
model_name_or_path: results/pre_rl_model

bf16: true

# Enhanced training for 96GB
max_steps: 200            # Can increase for better results
num_train_epochs: 1.0

save_strategy: "steps"

save_steps: 25            # Less frequent saves with more memory
do_eval: true
save_final_model: true

eval_strategy: steps
eval_steps: 10            # Less frequent eval

logging_steps: 1
logging_strategy: steps

# 96GB optimized batch sizes
train_batch_size: 128     # Much larger than 32
per_device_train_batch_size: 4
generation_aggregation_steps: 16  # Increased from 8

# Enhanced generations for 96GB
num_generations: 32       # 4x more than basic mono-GPU
temperature: 0.7
unbias_log_probabilities: true

learning_rate: 0.000001
beta: 0.04

sync_ref_model: false     
ref_model_mixup_alpha: 0.9
ref_model_sync_steps: 32

# Can use full-size student model with 96GB!
student_model: "bespokelabs/Bespoke-Stratos-7B"  # Full size instead of small
student_model_init_kwargs: null

offload_untrained_models: false  # Keep ALL models on GPU!

# Larger context lengths with 96GB
max_prompt_length: 8192   # 4x larger than basic
max_completion_length: 8192  # 2x larger than basic

# Enhanced reward coefficients for better training
answer_log_prob_coeff: [1, 0.01]
kl_penalty_reward_coeff: [3, 0.03]  # Back to original values
normalize_log_prob_fn: null
clip_log_prob: 100000
normalize_kl_fn: null
clip_kl: 100000
reduction_log_prob_fn: ["mean", "min"]
reduction_kl_fn: ["mean", "max"]
use_schulman_kl_estimation: false
not_matched_penalty: -1.0
unbias_teacher_log_probs: true
unbias_student_log_probs_temp: 0.7

save_completions_probability: 0.1  # Log more completions

lr_scheduler_type: "constant"
lr_scheduler_kwargs: ~

wandb_project: rl4lm_teacher_96gb

log_ctx_name: 96gb_gr${num_generations}_${max_prompt_length}ctx_${max_completion_length}gen

wandb_run_name: ${trainer_log_name}_96gb

output_dir: ${results_dir}/rlt_teacher_96gb/${exp_name}

# Use local vLLM (no server needed)
vllm_port: 8765
use_vllm: true
use_vllm_server: false
vllm_host:
num_vllm_clients: 1 