defaults:
  - override /model_cfg@_global_: qwen14b
  - override /data_cfg@_global_: teacher_bespoke_stratos
  - override /trainer_cfg@_global_: teacher_grpo
  - _self_

model_name_or_path: results/step-1_SFT_fused
use_peft: true
load_in_4bit: true

bf16: true

max_steps: 125
num_train_epochs: 1.0

save_strategy: "steps"

save_steps: 25
do_eval: true
save_final_model: true

eval_strategy: steps
eval_steps: 5

logging_steps: 1
logging_strategy: steps

train_batch_size: 64
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
num_generations: 16
generation_aggregation_steps: 8

temperature: 0.65
unbias_log_probabilities: true

learning_rate: 0.000001
beta: 0.04

sync_ref_model: true
ref_model_mixup_alpha: 0.9
ref_model_sync_steps: 32

student_model: "bespokelabs/Bespoke-Stratos-7B"
student_model_init_kwargs: null

offload_untrained_models: true

max_prompt_length: 8192
max_completion_length: 8192

answer_log_prob_coeff: [1, 0.01]
kl_penalty_reward_coeff: [3, 0.03]
normalize_log_prob_fn: null
clip_log_prob: 100000
normalize_kl_fn: null
clip_kl: 100000
reduction_log_prob_fn: ["mean", "min"]
reduction_kl_fn: ["mean", "max"]
use_schulman_kl_estimation: false
not_matched_penalty: -1.0
unbias_teacher_log_probs: true
unbias_student_log_probs_temp: 0.7

save_completions_probability: 0.1

lr_scheduler_type: "constant"
lr_scheduler_kwargs: ~

wandb_project: RLT_96GB_Teacher

log_ctx_name: gr${num_generations}_${max_prompt_length}ctx_${max_completion_length}gen

wandb_run_name: ${trainer_log_name}

output_dir: results/step-2_RLT_${exp_name}

vllm_port: 8765
use_vllm: true
use_vllm_server: false
vllm_host:
num_vllm_clients:

# vLLM Configuration
vllm_dtype: auto
vllm_gpu_memory_utilization: 0.4
vllm_max_model_len: 8192
vllm_quantization: fp8
