defaults:
  - override /model_cfg@_global_: qwen7bi
  - override /data_cfg@_global_: teacher_bespoke_stratos
  - override /trainer_cfg@_global_: grpo_mono_85gb  # Use 85GB trainer
  - _self_

# Optimized for 85GB with safety margin
model_name_or_path: results/pre_rl_model

bf16: true

# Training parameters for 85GB
max_steps: 200
num_train_epochs: 1.0

save_strategy: "steps"

save_steps: 25
do_eval: true
save_final_model: true

eval_strategy: steps
eval_steps: 10

logging_steps: 1
logging_strategy: steps

# 85GB optimized batch sizes
train_batch_size: 96      # Reduced from 128
per_device_train_batch_size: 3  # Reduced from 4
generation_aggregation_steps: 12  # Reduced from 16

# Adjusted generations for 85GB
num_generations: 24       # Reduced from 32
temperature: 0.7
unbias_log_probabilities: true

learning_rate: 0.000001
beta: 0.04

sync_ref_model: false     
ref_model_mixup_alpha: 0.9
ref_model_sync_steps: 32

# Use full-size student model (fits in 85GB)
student_model: "bespokelabs/Bespoke-Stratos-7B"
student_model_init_kwargs: null

offload_untrained_models: false  # Keep ALL models on GPU!

# Adjusted context lengths for 85GB
max_prompt_length: 6144   # Reduced from 8192
max_completion_length: 6144  # Reduced from 8192

# Balanced reward coefficients
answer_log_prob_coeff: [1, 0.01]
kl_penalty_reward_coeff: [3, 0.03]
normalize_log_prob_fn: null
clip_log_prob: 100000
normalize_kl_fn: null
clip_kl: 100000
reduction_log_prob_fn: ["mean", "min"]
reduction_kl_fn: ["mean", "max"]
use_schulman_kl_estimation: false
not_matched_penalty: -1.0
unbias_teacher_log_probs: true
unbias_student_log_probs_temp: 0.7

save_completions_probability: 0.08  # Slightly reduced

lr_scheduler_type: "constant"
lr_scheduler_kwargs: ~

wandb_project: rl4lm_teacher_85gb

log_ctx_name: 85gb_gr${num_generations}_${max_prompt_length}ctx_${max_completion_length}gen

wandb_run_name: ${trainer_log_name}_85gb

output_dir: ${results_dir}/rlt_teacher_85gb/${exp_name}

# Use local vLLM (no server needed)
vllm_port: 8765
use_vllm: true
use_vllm_server: false
vllm_host:
num_vllm_clients: 1 